version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "50051:50051"
    volumes:
      - ./product-service:/app
    working_dir: /app
    command: ["node", "productService.js"]
    depends_on:
      - kafka

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "50052:50052"
    volumes:
      - ./order-service:/app
    working_dir: /app
    command: ["node", "orderService.js"]
    depends_on:
      - kafka

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "50053:50053"
    volumes:
      - ./user-service:/app
    working_dir: /app
    command: ["node", "userService.js"]

  notification-service:
    build: ./notification-service
    container_name: notification-service
    volumes:
      - ./notification-service:/app
    working_dir: /app
    command: ["node", "notificationService.js"]
    depends_on:
      - kafka

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app
    working_dir: /app
    command: ["node", "apiGateway.js"]
    depends_on:
      - product-service
      - order-service
      - user-service
